//Login
export const CHANGE_ROUTE_LOGIN = 'CHANGE_ROUTE_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CHANGE_LOGIN_TYPE = 'LOGIN_CHANGE_LOGIN_TYPE';
export const LOGOUT = 'LOGOUT';